x-logging-config:
  &logging-config
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

services:
  factorio:
    image: factoriotools/factorio:2.0.76-rootless
    container_name: app-${SERVICE}
    restart: unless-stopped
    volumes:
      - '/mnt/Vault/Configuration/factorio/:/factorio'
    logging: *logging-config