x-logging-config:
  &logging-config
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

configs:
  ts-serve:
    content: |
      {"TCP":{"443":{"HTTPS":true}},
      "Web":{"$${TS_CERT_DOMAIN}:443":
          {"Handlers":{"/":
          {"Proxy":"http://127.0.0.1:3000"}}}},
      "AllowFunnel":{"$${TS_CERT_DOMAIN}:443":false}}

services:
  tailscale:
    image: tailscale/tailscale:latest # Image to be used
    container_name: tailscale-karakeep # Name for local container management
    hostname: karakeep # Name used within your Tailscale environment
    environment:
      - TS_AUTHKEY=${TS_AUTHKEY}
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_SERVE_CONFIG=/config/serve.json # Tailscale Serve configuration to expose the web interface on your local Tailnet - remove this line if not required
      - TS_USERSPACE=false
      - TS_ENABLE_HEALTH_CHECK=true # Enable healthcheck endpoint: "/healthz"
      - TS_LOCAL_ADDR_PORT=127.0.0.1:41234 # The <addr>:<port> for the healthz endpoint
      #- TS_ACCEPT_DNS=true # Uncomment when using MagicDNS
      - TS_AUTH_ONCE=true
    configs:
      - source: ts-serve
        target: /config/serve.json
    volumes:
      - '/mnt/Vault/Configuration/tailscale/state-karakeep:/var/lib/tailscale'
    devices:
      - /dev/net/tun:/dev/net/tun # Network configuration for Tailscale to work
    cap_add:
      - net_admin # Tailscale requirement
    #ports:
    #  - 0.0.0.0:${SERVICEPORT}:${SERVICEPORT} # Binding port ${SERVICE}PORT to the local network - may be removed if only exposure to your Tailnet is required
    # If any DNS issues arise, use your preferred DNS provider by uncommenting the config below
    # dns: 
    #   - ${DNS_SERVER}
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:41234/healthz"] # Check Tailscale has a Tailnet IP and is operational
      interval: 1m # How often to perform the check
      timeout: 10s # Time to wait for the check to succeed
      retries: 3 # Number of retries before marking as unhealthy
      start_period: 10s # Time to wait before starting health checks
    restart: always

  web:
    image: ghcr.io/karakeep-app/karakeep:0.31.0
    restart: unless-stopped
    network_mode: service:tailscale
    container_name: app-karakeep
    volumes:
      # By default, the data is stored in a docker volume called "data".
      # If you want to mount a custom directory, change the volume mapping to:
      # - /path/to/your/directory:/data
      - /mnt/Vault/Configuration/katakeep/data:/data
    depends_on:
      tailscale:
        condition: service_healthy
    environment:
      NEXTAUTH_URL: ${NEXTAUTH_URL}
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
      MEILI_ADDR: http://meilisearch:7700
      BROWSER_WEB_URL: http://chrome:9222
      OLLAMA_BASE_URL: http://ollama:11434
      INFERENCE_TEXT_MODEL: gemma3
      INFERENCE_IMAGE_MODEL: llava
      INFERENCE_LANG: english
      INFERENCE_ENABLE_AUTO_TAGGING: true
      INFERENCE_ENABLE_AUTO_SUMMARIZATION: true
      CRAWLER_STORE_PDF: true
      OTEL_TRACING_ENABLED: true
      # OPENAI_API_KEY: ... # Unused - use ollama for local analysis

      # You almost never want to change the value of the DATA_DIR variable.
      # If you want to mount a custom directory, change the volume mapping above instead.
      DATA_DIR: /data # DON'T CHANGE THIS
    logging: *logging-config
  chrome:
    image: gcr.io/zenika-hub/alpine-chrome:124
    container_name: app-karakeep-chrome
    restart: unless-stopped
    command:
      - --no-sandbox
      - --disable-gpu
      - --disable-dev-shm-usage
      - --remote-debugging-address=0.0.0.0
      - --remote-debugging-port=9222
      - --hide-scrollbars
    logging: *logging-config
  meilisearch:
    image: getmeili/meilisearch:v1.35.0
    container_name: app-karakeep-meilisearch
    restart: unless-stopped
    ports:
      - 7700:7700
    environment:
      MEILI_NO_ANALYTICS: "true"
      MEILI_MASTER_KEY: ${MEILI_MASTER_KEY}
    volumes:
      - /mnt/Vault/Configuration/katakeep/meilisearch:/meili_data
    logging: *logging-config
    ### Uncomment the below command after taking a meilisearch dump to upgrade the db.
    ### https://www.meilisearch.com/docs/learn/data_backup/dumps
    ### https://www.meilisearch.com/docs/guides/docker#generating-dumps-and-updating-meilisearch
    # command:
    #   - "meilisearch --import-dump /meili_data/dumps/"

  ollama: # CPU based LLM for processing bookmarks
    image: ollama/ollama:0.32.3
    logging: *logging-config

volumes:
  meilisearch:
  data:
