
x-logging-config:
  &logging-config
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"
    
services:
  plex:
    image: plexinc/pms-docker:1.41.8.9834-071366d65
    labels:
      logging: "promtail"
      stack: plex
    ports:
      - 32400:32400/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    environment:
      - TZ=America/Los_Angeles
      - PLEX_CLAIM=${PLEX_CLAIM_TOKEN} # https://plex.tv/claim
      - ADVERTISE_IP=http://minerva.local:32400
    restart: unless-stopped
    healthcheck: # Validate plex connectivity
      test: curl --connect-timeout 15 --silent --show-error --fail http://localhost:32400/identity
      interval: 1m00s
      timeout: 15s
      retries: 3
      start_period: 1m00s
    # devices: TODO add gpu mount for transcoding
    volumes:
      - '/mnt/Vault/Media:/data/media'
      - '/mnt/Vault/Configuration/Plex:/config'
    logging: *logging-config
  plex-prometheus: # provides prometheus metrics - allows grafana + alerting
    image: ghcr.io/jsclayton/prometheus-plex-exporter
    restart: unless-stopped
    labels:
      logging: "promtail"
      stack: plex
    environment:
      - PLEX_SERVER=http://plex:32400
      - PLEX_TOKEN=${PLEX_TOKEN}
    logging: *logging-config
  plex-tautulli: # combined with prometheus to monitor server
    image: ghcr.io/tautulli/tautulli:v2.15.2
    labels:
      logging: "promtail"
      stack: plex
    restart: unless-stopped
    ports:
      - 8181:8181
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - '/mnt/Vault/Configuration/Tautulli:/config:rw'
    logging: *logging-config
  plex-kometa-metadata:
    labels:
      logging: "promtail"
      stack: plex
    image: kometateam/kometa:v2.2.0
    restart: unless-stopped
    environment:
      - TZ=America/Los_Angeles
      - KOMETA_CONFIG=/config/config.yml
      - KOMETA_TIMES=02:00 # run this overnight
      - KOMETA_RUN=True
    volumes:
      - '/mnt/Vault/Configuration/PlexMetaManager:/config'
    logging: *logging-config
