{
 "title": "Plex Usage",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "Server Name",
    "query": {
     "query": "label_values(plays_total,server)"
    }
   },
   { "name": "user", "label": "Username", "query": { "query": "label_values(plays_total,user)" } },
   {
    "name": "library",
    "label": "Library Type",
    "query": {
     "query": "label_values(plays_total,library_type)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Library Storage Size",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "library_storage_total{server=\"$server\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Library Length",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(library_duration_total{server=\"$server\"}) by (server,library)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Estimated Bytes Transmitted",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 7, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rate(estimated_transmit_bytes_total{job=\"plex\", server=\"$server\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "options": {
    "content": "## [Plex](https://app.plex.com)\n## [Tautulli](http://minerva.local:30047)\n## [Overseer](minerva.local:30023)"
   }
  },
  {
   "title": "Plays by Library",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Plays" } },
   "targets": [
    {
     "expr": "sum(plays_total{user=~\"$user\", server=~\"$server\"}) by (library_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Seconds Played by Library",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(play_seconds_total{user=~\"$user\", server=~\"$server\"}) by (user, library_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Plays by Media Type",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "Plays" } },
   "targets": [
    {
     "expr": "sum(plays_total{user=~\"$user\", server=~\"$server\"}) by (title, library_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Type vs Total Active Streams",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "targets": [
    {
     "expr": "sum(plays_total{user=~\"$user\", server=~\"$server\"}) by (stream_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Type by User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "Plays" } },
   "targets": [
    {
     "expr": "sum(plays_total{user=~\"$user\", server=~\"$server\"}) by (user,stream_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Type vs Total Active Streams",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(plays_total{user=~\"$user\", server=~\"$server\"}) by (stream_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Stream Resolution by User",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "Plays" } },
   "targets": [
    {
     "expr": "sum(plays_total{user=~\"$user\", server=~\"$server\", stream_resolution!=\"\"}) by (user,stream_resolution)",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum(plays_total{user=\"$user\", server=\"$server\", stream_resolution!=\"\"}) by (user,stream_file_resolution)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Plays by User",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Plays" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(plays_total{user=~\"$user\", server=~\"$server\", library_type=~\"$library\"}) by (user)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Plays by Library",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "Plays" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(plays_total{user=~\"$user\", server=~\"$server\", library_type=~\"$library\"}) by (library_type)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Plays by Media Type",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "count(plays_total) by (library_type, title, child_title, grandchild_title, device_type, stream_resolution, user)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Size by Library",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(library_storage_total) by (server, library)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Plays by Media",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 52 },
   "fieldConfig": { "defaults": { "unit": "Plays" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(plays_total{user=~\"$user\", server=~\"$server\", library_type=~\"$library\"}) by (title)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}