x-logging-config:
  &logging-config
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"
    
services:
  tailscale:
    image: tailscale/tailscale:v1.96
    hostname: tailscale-minerva
    environment:
      - TS_AUTHKEY=${TAILSCALE_AUTH_TOKEN}
      - TS_EXTRA_ARGS=--advertise-tags=tag:container
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_ENABLE_METRICS=true
      - TS_ENABLE_HEALTH_CHECK=true 
    volumes:
      - '/mnt/Vault/Configuration/tailscale/state:/var/lib/tailscale'
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped
    network_mode: host
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://127.0.0.1:41234/healthz"] # Check Tailscale has a Tailnet IP and is operational
      interval: 1m # How often to perform the check
      timeout: 10s # Time to wait for the check to succeed
      retries: 3 # Number of retries before marking as unhealthy
      start_period: 10s # Time to wait before starting health checks
    logging: *logging-config
  # Experimentally adding tailscale as an auth provider.
  # See: https://github.com/tailscale/tsidp
  tsidp:
    image: ghcr.io/tailscale/tsidp:latest
    restart: unless-stopped
    volumes:
      - '/mnt/Vault/Configuration/tailscale/tsidp:/data'
    environment:
      - TAILSCALE_USE_WIP_CODE=1 # tsidp is experimental - needed while version <1.0.0
      - TS_STATE_DIR=/data # store persistent tsnet and tsidp state
      - TS_HOSTNAME=auth # Hostname on tailnet (becomes idp.your-tailnet.ts.net)
      - TSIDP_ENABLE_STS=1 # Enable OAuth token exchange
      - TS_AUTHKEY=${TAILSCALE_AUTH_IDP_TOKEN}
      - TS_ADVERTISE_TAGS=tag:tsidp
    logging: *logging-config