x-logging-config:
  &logging-config
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"
    
# Media Metadata and Request management
services:
  radarr: # Video Metadata
    container_name: radarr
    image: ghcr.io/hotio/radarr
    ports:
      - "7878:7878"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=7878/tcp 
    volumes:
      - '/mnt/Vault/Configuration/arr/radarr:/config'
      - '/mnt/Vault/Media/Data/Media:/data'
    logging: *logging-config
  sonarr: # Shows Metadata
    container_name: sonarr
    image: ghcr.io/hotio/sonarr
    ports:
      - "8989:8989"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=8989/tcp 
    volumes:
      - '/mnt/Vault/Configuration/arr/sonarr:/config'
      - '/mnt/Vault/Media/Data/Media:/data'
    logging: *logging-config
  seerr: # Managing requests
    image: ghcr.io/seerr-team/seerr:latest
    init: true
    container_name: seerr
    environment:
      - PUID=1000
      - PGID=1000
      - LOG_LEVEL=debug
      - TZ=America/Pacific
      - PORT=5055 #optional
    ports:
      - 5055:5055
    volumes:
      -  '/mnt/Vault/Configuration/arr/seerr:/app/config'
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:5055/api/v1/settings/public || exit 1
      start_period: 20s
      timeout: 3s
      interval: 15s
      retries: 3
    restart: unless-stopped
    logging: *logging-config
  bazarr: # Subtitle Metadata
    container_name: bazarr
    image: ghcr.io/hotio/bazarr
    ports:
      - "6767:6767"
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=Etc/UTC
      - WEBUI_PORTS=6767/tcp 
    volumes:
      - /<host_folder_config>:/config
      - /<host_folder_data>:/data