---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Media:
    - Jellyfin:
        href: https://jellyfin.comet-stork.ts.net
        description: Home Jellyfin Server for Movie, Show, Music and Book streaming.
        widget:
            type: jellyfin
            url: http://100.93.135.76:8096
            key: {{HOMEPAGE_VAR_JELLYFIN_API}}
            version: 2 # optional, default is 1
            enableBlocks: true # optional, defaults to false
            enableNowPlaying: true # optional, defaults to true
            enableUser: true # optional, defaults to false
            enableMediaControl: false # optional, defaults to true
            showEpisodeNumber: true # optional, defaults to false
            expandOneStreamToTwoRows: false # optional, defaults to true
    - Bazarr:
        href: https://bazarr.comet-stork.ts.net
        description: Bazarr Subtitle Service
        widget:
            type: bazarr
            url: http://100.87.59.121
            key: {{HOMEPAGE_VAR_BAZARR_API}}
    - Radarr:
        href: https://radarr.comet-stork.ts.net
        description: Radarr Movie Metadata Service
        widget:
            type: radarr
            url: http://100.113.174.100
            key: {{HOMEPAGE_VAR_RADARR_API}}
            enableQueue: true # optional, defaults to false
    - Sonarr:
        href: https://sonarr.comet-stork.ts.net
        description: Sonarr Show Metadata Service
        widget:
            type: sonarr
            url: http://100.126.40.118
            key: {{HOMEPAGE_VAR_SONARR_API}}
            enableQueue: true # optional, defaults to false
    - Seerr:
        href: https://seerr.comet-stork.ts.net
        description: Seerr Media Requests
        widget:
            type: seerr
            url: http://100.104.237.63
            key: {{HOMEPAGE_VAR_SEERR_API}}

- Intranet:
    - Portainer:
        href: http://localhost/
        description: Portainer portal
        widget:
            type: portainer
            url: https://portainer.host.or.ip:9443
            env: Minerva
            #key: ptr_accesskeyaccesskeyaccesskeyaccesskey
    - Grafana:
        description: Homelab Dashboards and Monitoring
        widget:
            type: grafana
            version: 2 # optional, default is 1
            url: http://grafana.host.or.ip:port
            #username: username
            #password: password

- Configuration:
    - Homelab Configuration:
        href: https://github.com/worldofzero/homelab 
        description: Homelab configuration on GitHub 
    - Tailscale:
        href: https://login.tailscale.com/admin
        descripption: Tailscale admin portal for Tailnet management

- Machines:
    - Minerva:
        widget:
            type: tailscale
            deviceid: nTacDWpKGb11CNTRL
            key: {{HOMEPAGE_VAR_TS_APIKEY}}
    - Hestia:
        widget:
            type: tailscale
            deviceid: nbLpPXcJBH11CNTRL
            key: {{HOMEPAGE_VAR_TS_APIKEY}}
    - Athena:
        widget:
            type: tailscale
            deviceid: nJgUqg5CNTRL
            key: {{HOMEPAGE_VAR_TS_APIKEY}}