services:
  fenrus:
    image: revenz/fenrus:latest
    labels:
      logging: "promtail"
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - ./data:/app/data