
x-logging-config:
  &logging-config
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"

services:
  fenrus:
    image: revenz/fenrus:23.08
    labels:
      logging: "promtail"
      stack: fenrus
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      - TZ=America/Los_Angeles
    volumes:
      - /mnt/Vault/Configuration/fenrus:/app/data
    logging: *logging-config