# This is for the full monitoring stack to simplify things

x-logging-config:
  &logging-config
  driver: "json-file"
  options:
    max-size: "1m"
    max-file: "1"
    tag: "{{.Name}}"
    
services:
  readarr: # book metadata
  radarr: # video metadata
  sonarr: # show metadata
  overseerr: # requests